# OBJS specifies files to compile
OBJS = 01_hello_SDL.cpp

OBJ_NAME = 01_hello_SDL

CC = g++

COMPILER_FLAGS = -Wall

LINKER_FLAGS = -lSDL2

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)


