# OBJS specifies files to compile
OBJS = 02_event.cpp

OBJ_NAME = 02_event

CC = g++

COMPILER_FLAGS = -Wall

LINKER_FLAGS = -lSDL2

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)


